movieblog/baza/urls.py
from django.urls import path
from . import views

app_name = "baza"

urlpatterns = [
	path('', views.home_page, name='home'),
	path('movie/<int:id>', views.movie_page, name='movie_page'),
	path('movie/search/', views.movie_page_by_name, name='movie_page_by_name'),
	path('comment/<int:id>', views.post_comment, name='post_comment'),
	path('deletecomment/<int:id>', views.delete_comment, name='delete_comment'),
	path('changecomment/<int:id>', views.change_comment, name='change_comment'),
	path('addfilm/', views.add_movie, name='add_movie'),
	path('changefilm/<int:id>', views.change_movie, name='change_movie')
]

movieblog/movieblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('baza.urls')),
	path('account/', include('nalozi.urls'))
]

movieblog/nalozi/urls.py
from django.urls import path
from . import views

app_name = "nalozi"

urlpatterns = [
	path('login', views.login, name='login'),
	path('logout', views.logout, name='logout'),
	path('register', views.register, name='register'),
	path('userpage', views.userpage, name='userpage')
]

movieblog/baza/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
	original_language = models.CharField(max_length=2)
	original_title = models.CharField(max_length=100)
	release_date = models.DateTimeField()
	revenue = models.IntegerField(default=0)
	runtime = models.IntegerField(default=0)
	likes = models.IntegerField(default=0)
	dislikes = models.IntegerField(default=0)
	
	def __str__(self):
		return self.original_title
	
	def is_successful(self):
		return self.revenue >= 150000000
	
	def is_long(self):
		return self.runtime >= 180
	
	def is_liked(self):
		return self.likes > self.dislikes
	
	def most_popular(self):
		return self.revenue >= 600000000

class Comment(models.Model):
	username = models.CharField(max_length=50)
	review = models.TextField()
	date = models.DateTimeField(auto_now_add=True)
	movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
	
	def __str__(self):
		return self.review

movieblog/baza/forms.py
from django import forms
import datetime

class CommentForm(forms.Form):
	review = forms.CharField(max_length=2000)
	rating = forms.CharField(widget=forms.Select(choices=[('like', 'like'), ('dislike', 'dislike')]), required=False)

class MovieForm(forms.Form):
	original_language = forms.CharField(max_length=2)
	original_title = forms.CharField(max_length=100)
	release_date = forms.DateTimeField(initial=datetime.date.today)
	revenue = forms.IntegerField()
	runtime = forms.IntegerField()

movieblog/baza/views.py
from django.shortcuts import render, get_object_or_404, redirect
from baza.models import Movie, Comment
from datetime import date
from django.http import HttpResponse
from .forms import *
from django.forms.models import model_to_dict

# Create your views here.
def home_page(request):
	popular_movies = Movie.objects.filter(revenue__gte=650000000)
	return render(request, 'home.html', {'movies': popular_movies})

def movie_page(request, id):
	mov = get_object_or_404(Movie, pk=id)
	comments = Comment.objects.filter(movie=id)
	form = CommentForm()
	return render(request, 'movie_page.html', {'movie': mov, 'comments': comments, 'form': form})

def movie_page_by_name(request):
	mov_title = request.POST.get('query', '')
	mov_title = mov_title.title()
	mov = get_object_or_404(Movie, original_title=mov_title)
	comments = Comment.objects.filter(movie=mov)
	form = CommentForm()
	return render(request, 'movie_page.html', {'movie': mov, 'comments': comments, 'form': form})

def post_comment(request, id):
	mov = get_object_or_404(Movie, pk=id)
	comments = Comment.objects.filter(movie=id)
	if request.method == 'POST':
		form = CommentForm(request.POST or None)
		if form.is_valid():
			review = request.POST.get('review', '')
			rating = request.POST.get('rating', '')
			if rating == 'like':
				mov.likes += 1
			else:
				mov.dislikes += 1
			mov.save()
			comment = Comment(username=request.user.username, review=review, date=date.today(), movie=mov)
			comment.save()
		else:
			HttpResponse('comment error')
	
	return redirect('baza:movie_page', id=id)
	
def delete_comment(request, id):
	if request.user.is_authenticated:
		comment = Comment.objects.get(id=id)
		comment.delete()
		return redirect('nalozi:userpage')

def change_comment(request, id):
	form = CommentForm()
	comment = Comment.objects.get(id=id)
	if request.user.is_authenticated:
		
		if request.method == 'POST':
			form = CommentForm(request.POST or None)
			if form.is_valid():
				form = request.POST
				new_review = form.get('review', '')
				comment.review = new_review
				comment.save()
				return redirect('nalozi:userpage')
			else:
				return HttpResponse('comment error')
	
	return render(request, 'change_comment.html', {'form': form, 'comment': comment})

def add_movie(request):
	if request.user.is_authenticated:
		form = MovieForm()
		if request.method == 'POST':
			form = MovieForm(request.POST or None)
			if form.is_valid():
				form = request.POST
				or_title = form.get('original_title', '')
				or_lang = form.get('original_language', '')
				date = form.get('release_date', '')
				revenue = form.get('revenue', '')
				runtime = form.get('runtime', '')
				mov = Movie(original_language=or_lang, original_title=or_title, release_date=date,
					revenue=revenue, runtime=runtime)
				mov.save()
				return redirect('nalozi:userpage')
		return render(request, 'add_movie.html', {'form': form})
	else:
		HttpResponse('movie adding error')

def change_movie(request, id):
	if request.user.is_authenticated:
		mov = get_object_or_404(Movie, pk=id)
		form = MovieForm(initial=model_to_dict(mov))
		if request.method == 'POST':
			form = MovieForm(request.POST or None)
			if form.is_valid():
				form = request.POST
				mov.original_title = form.get('original_title', '')
				mov.original_language = form.get('original_language', '')
				mov.release_date = form.get('release_date', '')
				mov.revenue = form.get('revenue', '')
				mov.runtime = form.get('runtime', '')
				mov.save()
				return redirect('baza:home')
		return render(request, 'change_movie.html', {'form': form, 'mid': id})
	else:
		HttpResponse('movie changing error')

movieblog/baza/templates/base.html
<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<!-- Bootstrap CSS -->
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
		<title>Home page</title>
	</head>
	<body>
		<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
		  <a class="navbar-brand" href="{% url 'baza:home' %}">moviedb</a>

		  <div class="collapse navbar-collapse" id="navbarColor01">
			<ul class="navbar-nav mr-auto">
			{% if user.is_authenticated %}
			  <li class="nav-item">
				<a class="nav-link" href="{% url 'nalozi:userpage' %}">{{user.username}}</a>
			  </li>
			  <li class="nav-item">
				<a class="nav-link" href="{% url 'nalozi:logout' %}">Log out</a>
			  </li>
			{% else %}
			  <li class="nav-item">
				<a class="nav-link" href="{% url 'nalozi:login' %}">Log in</a>
			  </li>
			{% endif %}
			  <li class="nav-item">
				<a class="nav-link" href="{% url 'nalozi:register' %}">Sign up</a>
			  </li>
			</ul>
			<form class="form-inline my-2 my-lg-0" action="{% url 'baza:movie_page_by_name' %}" method="post">
			  {% csrf_token %}
			  <input class="form-control mr-sm-2" type="text" placeholder="Search" id="query" name="query">
			  <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
			</form>
		  </div>
		</nav>
		
		{% block content %}
		
		{% endblock %}
	</body>

movieblog/baza/templates/change_comment.html
{% extends 'base.html' %}

{% block content %}

	<h3>Stari komentar:</h3>
	<p> {{comment.review}} </p>
	<br>
	<br>
	<h3>Novi komentar:</h3>
	<form action="{% url 'baza:change_comment' comment.id %}" method="post">
		{% csrf_token %}
		{{ form }}
		<button type="submit" class="btn btn-warning">Izmeni</button>
	</form>
	

{% endblock %}

movieblog/baza/templates/change_movie.html
{% extends 'base.html' %}

{% block content %}
	<form action="{% url 'baza:change_movie' mid %}" method="post">
		{% csrf_token %}
		<table border="1" style="width: 30%;">
			{{form}}
		</table>
		<input type="submit" value="Submit" class="btn btn-danger">
	</form>
	
	<style>
		td {
		  padding: 7px;
		  width: 40%;
		}
	</style>

{% endblock %}

movieblog/baza/templates/home.html
{% extends 'base.html' %}

{% block content %}

	<div class="container">
		<h1 class="text-center">Dobrodosli na glavnu stranicu!</h1>
		{% for movie in movies %}
			<a href="{% url 'baza:movie_page' movie.id %}"><h4 class="text-center">{{ movie.original_title }}</h4></a>
		{% endfor %}
	</div>

{% endblock %}

movieblog/baza/templates/movie_page.html
{% extends 'base.html' %}

{% block content %}

	<h1 class="text-center" style="padding-bottom: 60px;"> {{ movie.original_title}} </h1>
	<h4 class="text-center"> Jezik: {{ movie.original_language}} </h4>
	<h4 class="text-center"> Premijera: {{ movie.release_date}} </h4>
	<h4 class="text-center"> Box office: {{ movie.revenue}}$ </h4>
	<h4 class="text-center"> Trajanje: {{ movie.runtime}} </h4>
	
	{% if movie.is_liked %}
		<h4 class="text-center" style="color: green;"> Ljudi obozavaju film! </h4>
	{% endif %}
	
	<div style="padding-top: 100px;"></div>
	{% if user.is_authenticated %}
	<form action="{% url 'baza:post_comment' movie.id %}" method="post">
		{% csrf_token %}
		<!--
		<div class="mb-3">
		  <label for="comment" class="form-label">Komentar</label>
		  <textarea class="form-control" id="comment" name="comment" rows="3"></textarea>
		</div>
		<div class="d-flex btn-group justify-content-center" role="group" aria-label="Rejting" style="padding-left: 30%; padding-right: 30%">

		  <button type="button" class="btn btn-success" value="like" id="like" name="like">Like</button>
		  <button type="button" class="btn btn-danger"  value="dislike" id="dislike" name="dislike">Dislike</button>
	
		  <!--
		  <input type="button" value="Like" class="btn btn-success" id="like" name="like">
		  <input type="button" value="Dislike" class="btn btn-danger" id="dislike" name="dislike">
		  
		</div>
		-->
		<div style="padding-left: 42%; padding-right: 45%; padding-top: 15px; justify-content: space-between;">
			<table border="1" style="width: 30%;">
				{{form}}
			</table>
			<div style="margin: 15px;">
				<input type="submit" value="Postavi komentar" class="btn btn-success">
			</div>
		</div>
	</form>
	<div style="padding-left: 45%; padding-right: 45%; padding-top: 2px;">
	<form action="{% url 'baza:change_movie' movie.id %}">
		{% csrf_token %}
		<button type="submit" class="btn btn-warning">Izmeni film</button>
	</form>
	</div>
	{% else %}
		<h6 class="text-center">Morate da se ulogujete da biste ostavili komentare!</h6>
	{% endif %}
	
	<div style="padding-top: 40px;"></div>
	
	<h6 class="text-center">Komentari</h6>
	<hr>
	
	<div style="padding-top: 40px;">
	{% for comment in comments %}
		<li class="media">
        <div class="media-body">
          <h5 class="mt-0 mb-1 text-center">{{comment.username}}</h5>
          <p class="text-center">{{comment.review}}</p>
          <br />
          <p class="text-center">{{comment.date}}</p>
          <hr>
        </div>
      </li>
	{% endfor %}
	</div>
	
	<style>
		td {
		  padding: 7px;
		  width: 40%;
		}
	</style>

{% endblock %}