movieblog/baza/urls.py
from django.urls import path
from . import views

app_name = "baza"

urlpatterns = [
	path('', views.home_page, name='home'),
	path('movie/<int:id>', views.movie_page, name='movie_page'),
	path('movie/search/', views.movie_page_by_name, name='movie_page_by_name'),
	path('comment/<int:id>', views.post_comment, name='post_comment'),
	path('deletecomment/<int:id>', views.delete_comment, name='delete_comment'),
	path('changecomment/<int:id>', views.change_comment, name='change_comment'),
	path('addfilm/', views.add_movie, name='add_movie'),
	path('changefilm/<int:id>', views.change_movie, name='change_movie')
]

movieblog/movieblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('baza.urls')),
	path('account/', include('nalozi.urls'))
]

movieblog/nalozi/urls.py
from django.urls import path
from . import views

app_name = "nalozi"

urlpatterns = [
	path('login', views.login, name='login'),
	path('logout', views.logout, name='logout'),
	path('register', views.register, name='register'),
	path('userpage', views.userpage, name='userpage')
]

movieblog/nalozi/models.py
from django.db import models

# Create your models here.

movieblog/nalozi/forms.py
from django import forms

class RegisterForm(forms.Form):
	first_name = forms.CharField(max_length=30)
	last_name = forms.CharField(max_length=60)
	username = forms.CharField(max_length=50)
	password = forms.CharField(max_length=40, widget=forms.PasswordInput)
	
class LoginForm(forms.Form):
	username = forms.CharField(max_length=50)
	password = forms.CharField(max_length=40, widget=forms.PasswordInput)

movieblog/nalozi/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate
from django.contrib.auth import login as django_login
from django.contrib.auth import logout as django_logout
from django.http import HttpResponse
from django.contrib.auth.models import User
from baza.models import Comment
from .forms import *

# Create your views here.
def register(request):
	form = RegisterForm()
	if request.method == 'POST':
		form = RegisterForm(request.POST or None)
		if form.is_valid():
			username = request.POST.get('username', '')
			password = request.POST.get('password', '')
			first_name = request.POST.get('first_name', '')
			last_name = request.POST.get('last_name', '')
			user = User.objects.create_user(username=username, password=password,
				first_name=first_name, last_name=last_name)
		
			user = authenticate(username=user.username, password=password)
			django_login(request, user)
			return redirect('baza:home')
		else:
			form = RegisterForm()
			return render(request, 'register.html', {'form': form, 'error': 'Problem u registraciji. Pokusajte ponovo.'})
	
	return render(request, 'register.html', {'form': form})

def login(request):
	if request.user.is_authenticated:
		return redirect('baza:home')
	
	form = LoginForm()
	
	if request.method == 'POST':
		form = LoginForm(request.POST or None)
		if form.is_valid():
			form = request.POST
			username = form.get('username', '')
			password = form.get('password', '')
			user = authenticate(request, username=username, password=password)
			if user is not None:
				django_login(request, user)
				return redirect('baza:home')
			else:
				form = LoginForm()
				return render(request, 'login.html', {'form': form, 'error': 'Losi kredencijali. Ulogujte se ponovo.'})
		else:
			form = LoginForm()
			return render(request, 'login.html', {'form': form, 'error': 'Losi kredencijali. Ulogujte se ponovo.'})
	
	return render(request, 'login.html', {'form': form})

def logout(request):
	if request.user.is_authenticated:
		django_logout(request)
		return redirect('baza:home')
	
	return HttpResponse('logout')

def userpage(request):
	if request.user.is_authenticated:
		reviews = Comment.objects.filter(username=request.user.username)
		return render(request, 'userpage.html', {'user': request.user, 'reviews': reviews})
	else:
		return HttpResponse('user error')

movieblog/nalozi/templates/login.html
{% extends 'base.html' %}

{% block content %}

	{% if error %}
        <i style="color: red">{{ error }}</i>
        <br>
    {% endif %}

	<form action="{% url 'nalozi:login' %}" method="post">
		{% csrf_token %}
		<div style="padding-left: 10%; padding-top: 20px;">
			<table border="1" style="width: 30%;">
			{{form}}
			</table>
			<input type="submit" value="Register" class="btn btn-danger">
		</div>
	</form>
	
	<style>
		td {
		  padding: 7px;
		  width: 40%;
		}
	</style>

{% endblock %}

movieblog/nalozi/templates/register.html
{% extends 'base.html' %}

{% block content %}
	{% if error %}
        <i style="color: red">{{ error }}</i>
        <br>
    {% endif %}

	<form action="{% url 'nalozi:register' %}" method="post">
		{% csrf_token %}
		<div style="padding-left: 10%; padding-top: 20px;">
			<table border="1" style="width: 30%;">
			{{form}}
			</table>
			<input type="submit" value="Register" class="btn btn-danger">
		</div>
	</form>
	
	<style>
		td {
		  padding: 7px;
		  width: 40%;
		}
	</style>

{% endblock %}

movieblog/nalozi/templates/userpage.html
{% extends 'base.html' %}

{% block content %}
	<div class="container">
		<h3>{{user.first_name}} {{user.last_name}}</h3>
		<h5 style="font-weight: 2;">@{{user.username}}</h5>
		<h5 style="font-weight: 2;">Uclanio se: {{user.date_joined}}</h5>
		<h4 style="padding-top: 30px;"> Mozete da dodate filmove! </h4>
		<div class="d-flex btn-group justify-content-right" role="group" aria-label="Rejting" style="display:inline-block;">
		  
		  <form action="{% url 'baza:add_movie' %}" method="get">
			{% csrf_token %}
			<button type="submit" class="btn btn-success">Dodaj film</button>
		  </form>
		</div>
		
		<h4 style="padding-top: 60px;">Komentari:</h4>
		{% for review in reviews %}
			<h5> Komentar na: {{review.movie.original_title}}</h3>
			<div> 
				<div style="display:inline-block;">
				<p> {{review.review}}</p>
				</div>
				<div class="d-flex btn-group justify-content-right" role="group" aria-label="Rejting" style="padding-left: 80%; display:inline-block;">
				  <form action="{% url 'baza:change_comment' review.id %}" method="get">
					{% csrf_token %}
					<button type="submit" class="btn btn-warning">Izmeni</button>
				  </form>
				  <form action="{% url 'baza:delete_comment' review.id %}">
					{% csrf_token %}
					<button type="submit" class="btn btn-danger">Obrisi</button>
				  </form>
				</div>
			</div>
			<p> Napravljeno: {{review.date}}</p>
			<hr>
		{% endfor %}
			
	</div>

{% endblock %}